### PR TITLE
Stories media-block heating

### PR DESCRIPTION
**Pull request by GermanVor**

### CODE REVIEW

**Comment by GermanVor** [comment]
I also thinking about such property as `heating?: Number | true`

```
// heating === undefined, old version
{currentStory?.media && (
    <div className={b('media-block')}>
        <MediaRenderer media={currentStory.media} />
    </div>
)}

// heating === true, heating all items
props.items.map(({media}, i) =>
    media ? (
        <div
            className={b('media-block', {visible: i === props.storyIndex})}
            key={i}
        >
            <MediaRenderer media={media} />
        </div>
    ) : null,
})

// isNumber(heating), heating +-heatingCount items
const leftIdx = Math.min(Math.max(props.storyIndex - heating, 0), props.storyIndex)
const rightIdx = Math.max(Math.min(props.storyIndex + heating, props.items.length - 1), props.storyIndex)

range({from: leftIdx, to: rightIdx}).map((mediaIdx) =>
    media ? (
        <div
            className={b('media-block', {visible: mediaIdx === props.storyIndex})}
            key={mediaIdx}
        >
            <MediaRenderer media={props.items[mediaIdx].media} />
        </div>
    ) : null,
)
```

**Comment by GermanVor** [comment]
In this PR I tried to solve problem of long Media content loadings - when you change stories, Media content is not loaded yet and there is empty background.

**Comment by GermanVor** [comment]
May be it have also sense pass `keepMounted` to the `Modal` if `heating` property defined

**Comment by GermanVor** [comment]
https://github.com/gravity-ui/components/blob/stories-refactoring/src/components/Stories/components/VideoView/VideoView.tsx#L18

Browser will have to download all Media content before show it

@DarkGenius

**Comment by DarkGenius** [comment]
Let's add props `heating` and `keepMounted`

**Pull request closed without merging**
